// Auto-generated from فہرست خطبات index. Do not hand-edit titles.
import type { Localized } from "@/lib/i18n";
export interface SermonTopicEntry { id: string; title: Localized; page: number; }
export const SERMON_TOPICS: SermonTopicEntry[] = [
  { id: "_Toc29194034", title: { ur: "ایمانیات (عقائد و نظریات)", en: "Beliefs & Doctrines (Imaniyat)", ar: "العقائد والمعتقدات" }, page: 15 },
  { id: "_Toc29194059", title: { ur: "عبادات", en: "Acts of Worship (Ibadat)", ar: "العبادات" }, page: 39 },
  { id: "_Toc45011938", title: { ur: "نکاح و طلاق", en: "Marriage & Divorce", ar: "النكاح والطلاق" }, page: 56 },
  { id: "_Toc29194075", title: { ur: "نکاح/شادی(مسنون طریقہ، ولیمہ، جہیز، رسومات)", en: "Marriage (Sunnah Method, Walimah, Dowry, Customs)", ar: "الزواج (الطريقة السنية، الوليمة، الجهاز، العادات)" }, page: 56 },
  { id: "_Toc29194071", title: { ur: "عقیقہ", en: "Aqiqah", ar: "العقيقة" }, page: 58 },
  { id: "_Toc29194076", title: { ur: "طلاق", en: "Divorce (Talaq)", ar: "الطلاق" }, page: 58 },
  { id: "_Toc29194082", title: { ur: "معاملات", en: "Transactions & Dealings", ar: "المعاملات" }, page: 58 },
  { id: "_Toc29194083", title: { ur: "معیشت وروزگار(معاشی نظام،مسائل، رزق حلال کی برکت وغیرہ)", en: "Economy & Livelihood (Economic System, Issues, Blessings of Halal Earnings)", ar: "الاقتصاد والمعيشة (النظام الاقتصادي، المسائل، بركة الرزق الحلال)" }, page: 58 },
  { id: "_Toc29194084", title: { ur: "تجارت کی اہمیت", en: "Importance of Trade", ar: "أهمية التجارة" }, page: 59 },
  { id: "_Toc45011945", title: { ur: "مزدوری و محنت کشی ، ملازمت", en: "Labor, Hard Work & Employment", ar: "العمل والكدح والوظيفة" }, page: 59 },
  { id: "_Toc29194086", title: { ur: "حلال و حرام", en: "Halal & Haram", ar: "الحلال والحرام" }, page: 59 },
  { id: "_Toc29194087", title: { ur: "سود", en: "Interest (Riba)", ar: "الربا" }, page: 60 },
  { id: "_Toc29194088", title: { ur: "قرض", en: "Loans & Debt", ar: "القرض" }, page: 60 },
  { id: "_Toc45011949", title: { ur: "بھیک مانگنا", en: "Begging", ar: "التسول" }, page: 60 },
  { id: "_Toc29194089", title: { ur: "سفارش", en: "Recommendation / Intercession", ar: "الشفاعة" }, page: 61 },
  { id: "_Toc29194138", title: { ur: "آداب معاشرت / آداب انسانیت", en: "Social Etiquette / Human Conduct", ar: "آداب المعاشرة / آداب الإنسانية" }, page: 61 },
  { id: "_Toc29194139", title: { ur: "معاشرتی مسائل اور ان کا حل", en: "Social Issues and Their Solutions", ar: "المسائل الاجتماعية وحلولها" }, page: 63 },
  { id: "_Toc45011953", title: { ur: "لڑائی جھگڑے", en: "Quarrels & Conflicts", ar: "النزاعات والخصومات" }, page: 64 },
  { id: "_Toc45011954", title: { ur: "ظلم و ستم ، ایذا دہی", en: "Oppression, Tyranny & Harm", ar: "الظلم والاضطهاد والإيذاء" }, page: 64 },
  { id: "_Toc29194140", title: { ur: "اختلاف رائے", en: "Difference of Opinion", ar: "اختلاف الرأي" }, page: 65 },
  { id: "_Toc29194141", title: { ur: "ٍصلح جوئی / اتحاد و اختلاف", en: "Reconciliation / Unity & Discord", ar: "المصالحة / الاتحاد والاختلاف" }, page: 65 },
  { id: "_Toc45011958", title: { ur: "حسن سلوک", en: "Good Conduct", ar: "حسن السلوك" }, page: 66 },
  { id: "_Toc45011959", title: { ur: "حقوق العباد", en: "Rights of People (Huquq al-Ibad)", ar: "حقوق العباد" }, page: 66 },
  { id: "_Toc29194145", title: { ur: "والدین کے حقوق اور اطاعت", en: "Rights of Parents & Obedience", ar: "حقوق الوالدين وطاعتهما" }, page: 67 },
  { id: "_Toc45011961", title: { ur: "زوجین کے حقوق", en: "Rights of Spouses", ar: "حقوق الزوجين" }, page: 68 },
  { id: "_Toc29194148", title: { ur: "اولاد کے حقوق (تربیت اولاد)", en: "Rights of Children (Upbringing)", ar: "حقوق الأولاد (تربية الأولاد)" }, page: 68 },
  { id: "_Toc29194151", title: { ur: "رشتہ داروں کے حقوق", en: "Rights of Relatives", ar: "حقوق الأقارب" }, page: 69 },
  { id: "_Toc29194149", title: { ur: "بڑوں (بزرگوں) کے حقوق", en: "Rights of Elders", ar: "حقوق الكبار" }, page: 69 },
  { id: "_Toc29194150", title: { ur: "ہمسایوں کے حقوق", en: "Rights of Neighbors", ar: "حقوق الجيران" }, page: 69 },
  { id: "_Toc29194154", title: { ur: "یتیموں کے حقوق", en: "Rights of Orphans", ar: "حقوق اليتامى" }, page: 70 },
  { id: "_Toc29194155", title: { ur: "فقراء کے حقوق", en: "Rights of the Poor", ar: "حقوق الفقراء" }, page: 70 },
  { id: "_Toc29194157", title: { ur: "میت کے حقوق (تعزیت)", en: "Rights of the Deceased (Condolence)", ar: "حقوق الميت (التعزية)" }, page: 70 },
  { id: "_Toc45011969", title: { ur: "راستے کے حقوق", en: "Rights of the Road", ar: "حقوق الطريق" }, page: 70 },
  { id: "_Toc29194161", title: { ur: "آداب", en: "Etiquette (Adab)", ar: "الآداب" }, page: 70 },
  { id: "_Toc29194162", title: { ur: "کھانے پینے کے آداب", en: "Etiquette of Eating & Drinking", ar: "آداب الأكل والشرب" }, page: 70 },
  { id: "_Toc29194163", title: { ur: "سونے جاگنے کے آداب", en: "Etiquette of Sleeping & Waking", ar: "آداب النوم والاستيقاظ" }, page: 70 },
  { id: "_Toc29194170", title: { ur: "لباس و پہننے کے آداب", en: "Etiquette of Clothing & Dress", ar: "آداب اللباس" }, page: 71 },
  { id: "_Toc45011974", title: { ur: "شرعی پردہ", en: "Shariah Veiling (Purdah)", ar: "الحجاب الشرعي" }, page: 71 },
  { id: "_Toc29194164", title: { ur: "اٹھنے بیٹھنے کے آداب", en: "Etiquette of Sitting & Standing", ar: "آداب الجلوس والقيام" }, page: 72 },
  { id: "_Toc29194166", title: { ur: "سلام و مصافحہ کے آداب", en: "Etiquette of Greeting & Handshake", ar: "آداب السلام والمصافحة" }, page: 72 },
  { id: "_Toc45011977", title: { ur: "ملاقات اور فون کرنے کے آداب", en: "Etiquette of Meeting & Phone Calls", ar: "آداب اللقاء والاتصال الهاتفي" }, page: 72 },
  { id: "_Toc45011978", title: { ur: "گفتگو کے آداب", en: "Etiquette of Conversation", ar: "آداب الحديث" }, page: 72 },
  { id: "_Toc29194168", title: { ur: "عیادت کے آداب", en: "Etiquette of Visiting the Sick", ar: "آداب العيادة" }, page: 72 },
  { id: "_Toc29194169", title: { ur: "ہدیہ و تحفہ کے لین دین کے آداب", en: "Etiquette of Giving & Receiving Gifts", ar: "آداب تبادل الهدايا" }, page: 72 },
  { id: "_Toc29194172", title: { ur: "دعوت و ضیافت کے آداب", en: "Etiquette of Invitation & Hospitality", ar: "آداب الدعوة والضيافة" }, page: 72 },
  { id: "_Toc29194174", title: { ur: "مہمان نوازی کے آداب", en: "Etiquette of Hospitality", ar: "آداب استقبال الضيوف" }, page: 72 },
  { id: "_Toc45011983", title: { ur: "سفر کے آداب", en: "Etiquette of Travel", ar: "آداب السفر" }, page: 72 },
  { id: "_Toc45011984", title: { ur: "جنازے اور چھینکنے کے آداب", en: "Etiquette of Funerals & Sneezing", ar: "آداب الجنازة والعطاس" }, page: 73 },
  { id: "_Toc29194175", title: { ur: "اخلاق و صفات حسنہ (اچھے اخلاق و صفات)", en: "Good Morals & Virtues", ar: "الأخلاق والصفات الحسنة" }, page: 73 },
  { id: "_Toc45011986", title: { ur: "احسان کا بدلہ احسان", en: "Returning Good for Good", ar: "الإحسان جزاء الإحسان" }, page: 73 },
  { id: "_Toc29194177", title: { ur: "تواضع", en: "Humility", ar: "التواضع" }, page: 74 },
  { id: "_Toc29194178", title: { ur: "امانت و دیانت", en: "Trust & Honesty", ar: "الأمانة والديانة" }, page: 74 },
  { id: "_Toc29194179", title: { ur: "عدل و انصاف", en: "Justice & Fairness", ar: "العدل والإنصاف" }, page: 74 },
  { id: "_Toc29194180", title: { ur: "صدق و سچائی / حفاظت زبان", en: "Truthfulness / Guarding the Tongue", ar: "الصدق / حفظ اللسان" }, page: 75 },
  { id: "_Toc29194181", title: { ur: "حفاظت نظر", en: "Guarding the Gaze", ar: "حفظ النظر" }, page: 75 },
  { id: "_Toc29194183", title: { ur: "عزم و استقامت", en: "Determination & Steadfastness", ar: "العزم والاستقامة" }, page: 76 },
  { id: "_Toc45011993", title: { ur: "محنت کی عظمت اور جذبہ حق", en: "Dignity of Labor & Passion for Truth", ar: "عظمة العمل وروح الحق" }, page: 76 },
  { id: "_Toc29194184", title: { ur: "ایفائے عہد", en: "Fulfilling Promises", ar: "الوفاء بالعهد" }, page: 76 },
  { id: "_Toc29194185", title: { ur: "اخلاص", en: "Sincerity (Ikhlas)", ar: "الإخلاص" }, page: 76 },
  { id: "_Toc29194186", title: { ur: "توکل علی اللہ اور اختیار اسباب", en: "Trust in Allah & Adopting Means", ar: "التوكل على الله والأخذ بالأسباب" }, page: 78 },
  { id: "_Toc29194187", title: { ur: "صبر و تحمل", en: "Patience & Tolerance", ar: "الصبر والتحمل" }, page: 78 },
  { id: "_Toc29194188", title: { ur: "قناعت", en: "Contentment", ar: "القناعة" }, page: 80 },
  { id: "_Toc29194189", title: { ur: "سادگی", en: "Simplicity", ar: "البساطة" }, page: 80 },
  { id: "_Toc29194190", title: { ur: "سخاوت", en: "Generosity", ar: "السخاء" }, page: 80 },
  { id: "_Toc29194191", title: { ur: "حیاء", en: "Modesty (Haya)", ar: "الحياء" }, page: 80 },
  { id: "_Toc29194192", title: { ur: "عفو و درگزر", en: "Forgiveness & Pardon", ar: "العفو والصفح" }, page: 80 },
  { id: "_Toc45012003", title: { ur: "شجاعت و بہادری", en: "Courage & Bravery", ar: "الشجاعة والبسالة" }, page: 80 },
  { id: "_Toc29194193", title: { ur: "صلہ رحمی", en: "Maintaining Kinship Ties", ar: "صلة الرحم" }, page: 80 },
  { id: "_Toc29194194", title: { ur: "نرمی", en: "Gentleness", ar: "الرفق" }, page: 81 },
  { id: "_Toc29194196", title: { ur: "حدود و قیود / اعتدال", en: "Limits & Moderation", ar: "الحدود والقيود / الاعتدال" }, page: 81 },
  { id: "_Toc29194197", title: { ur: "شکر", en: "Gratitude", ar: "الشكر" }, page: 82 },
  { id: "_Toc29194198", title: { ur: "ایثار و مواسات", en: "Altruism & Empathy", ar: "الإيثار والمواساة" }, page: 83 },
  { id: "_Toc29194199", title: { ur: "لایعنی سے اجتناب", en: "Avoiding the Meaningless", ar: "اجتناب اللغو" }, page: 83 },
  { id: "_Toc29194200", title: { ur: "متفرقات(صفات حسنہ)", en: "Miscellaneous (Good Traits)", ar: "متفرقات (الصفات الحسنة)" }, page: 83 },
  { id: "_Toc29194201", title: { ur: "اخلاق و صفات سیئہ(برے اخلاق و صفات)", en: "Bad Morals & Vices", ar: "الأخلاق والصفات السيئة" }, page: 84 },
  { id: "_Toc29194202", title: { ur: "خود غرضی", en: "Selfishness", ar: "الأنانية" }, page: 84 },
  { id: "_Toc29194204", title: { ur: "حرص و طمع", en: "Greed & Avarice", ar: "الحرص والطمع" }, page: 84 },
  { id: "_Toc29194205", title: { ur: "ریاکاری", en: "Ostentation (Riya)", ar: "الرياء" }, page: 84 },
  { id: "_Toc29194206", title: { ur: "بد گمانی", en: "Suspicion", ar: "سوء الظن" }, page: 84 },
  { id: "_Toc29194207", title: { ur: "تکبر", en: "Arrogance", ar: "التكبر" }, page: 84 },
  { id: "_Toc29194208", title: { ur: "جھوٹ", en: "Lying", ar: "الكذب" }, page: 85 },
  { id: "_Toc29194209", title: { ur: "خیانت و دھوکہ", en: "Betrayal & Deception", ar: "الخيانة والخداع" }, page: 85 },
  { id: "_Toc29194210", title: { ur: "وعدہ خلافی", en: "Breaking Promises", ar: "نقض العهد" }, page: 85 },
  { id: "_Toc29194211", title: { ur: "غیبت", en: "Backbiting", ar: "الغيبة" }, page: 85 },
  { id: "_Toc29194212", title: { ur: "حسد", en: "Envy", ar: "الحسد" }, page: 86 },
  { id: "_Toc45012022", title: { ur: "تعصب", en: "Prejudice", ar: "التعصب" }, page: 86 },
  { id: "_Toc29194213", title: { ur: "غصہ", en: "Anger", ar: "الغضب" }, page: 86 },
  { id: "_Toc29194214", title: { ur: "قطع تعلق", en: "Severing Ties", ar: "قطع العلاقة" }, page: 86 },
  { id: "_Toc29194215", title: { ur: "بد کرداری", en: "Misconduct", ar: "سوء الأخلاق" }, page: 86 },
  { id: "_Toc29194216", title: { ur: "بے حیائی", en: "Shamelessness", ar: "الفحشاء" }, page: 86 },
  { id: "_Toc29194220", title: { ur: "حب دنیا", en: "Love of the World", ar: "حب الدنيا" }, page: 87 },
  { id: "_Toc29194221", title: { ur: "حب مال و جاہ", en: "Love of Wealth & Status", ar: "حب المال والجاه" }, page: 87 },
  { id: "_Toc45012029", title: { ur: "مخلوق کی محبت", en: "Love of Creation", ar: "محبة المخلوق" }, page: 87 },
  { id: "_Toc29194223", title: { ur: "فضول خرچی", en: "Extravagance", ar: "الإسراف" }, page: 88 },
  { id: "_Toc29194225", title: { ur: "رشوت", en: "Bribery", ar: "الرشوة" }, page: 88 },
  { id: "_Toc29194229", title: { ur: "چوری/ ڈاکہ زنی", en: "Theft / Robbery", ar: "السرقة / السطو" }, page: 88 },
  { id: "_Toc29194230", title: { ur: "زنا", en: "Adultery (Zina)", ar: "الزنا" }, page: 88 },
  { id: "_Toc29194266", title: { ur: "ذکر و فکر", en: "Remembrance & Reflection", ar: "الذكر والفكر" }, page: 88 },
  { id: "_Toc29194057", title: { ur: "عمل(اہمیت ، ضرورت اور فضائل)", en: "Action (Importance, Necessity & Virtues)", ar: "العمل (الأهمية والضرورة والفضائل)" }, page: 88 },
  { id: "_Toc45012036", title: { ur: "اتباع سنت", en: "Following the Sunnah", ar: "اتباع السنة" }, page: 89 },
  { id: "_Toc45012037", title: { ur: "اتباع شریعت", en: "Following the Shariah", ar: "اتباع الشريعة" }, page: 90 },
  { id: "_Toc45012038", title: { ur: "اتباع علماء و صلحاء", en: "Following Scholars & the Righteous", ar: "اتباع العلماء والصلحاء" }, page: 91 },
  { id: "_Toc45012039", title: { ur: "قبولیت", en: "Acceptance (Qabuliyat)", ar: "القبولية" }, page: 91 },
  { id: "_Toc45012040", title: { ur: "حقوق اللہ", en: "Rights of Allah", ar: "حقوق الله" }, page: 91 },
  { id: "_Toc29194267", title: { ur: "تعلق مع اللہ/قرب الہی", en: "Connection with Allah / Divine Nearness", ar: "التعلق بالله / القرب الإلهي" }, page: 91 },
  { id: "_Toc45012042", title: { ur: "محبت، نصرت و رضائے الہیہ", en: "Divine Love, Help & Pleasure", ar: "المحبة والنصرة والرضا الإلهية" }, page: 92 },
  { id: "_Toc45012043", title: { ur: "مغفرت و رحمت الہیہ", en: "Divine Forgiveness & Mercy", ar: "المغفرة والرحمة الإلهية" }, page: 93 },
  { id: "_Toc45012044", title: { ur: "تسلیم و رضا بالقضاء", en: "Submission & Pleasure with Destiny", ar: "التسليم والرضا بالقضاء" }, page: 93 },
  { id: "_Toc29194268", title: { ur: "عبدیت", en: "Servitude (Ubudiyyah)", ar: "العبودية" }, page: 94 },
  { id: "_Toc45012046", title: { ur: "توبہ و استغفار، انابت الی اللہ", en: "Repentance & Turning to Allah", ar: "التوبة والاستغفار والإنابة إلى الله" }, page: 94 },
  { id: "_Toc45012047", title: { ur: "ذکر اللہ", en: "Remembrance of Allah", ar: "ذكر الله" }, page: 95 },
  { id: "_Toc29194270", title: { ur: "بسم اللہ کی برکات اور رموز", en: "Blessings & Secrets of Bismillah", ar: "بركات بسم الله وأسرارها" }, page: 97 },
  { id: "_Toc29194271", title: { ur: "درود شریف", en: "Durood Sharif", ar: "الصلاة على النبي" }, page: 97 },
  { id: "_Toc29194272", title: { ur: "دعا", en: "Supplication (Dua)", ar: "الدعاء" }, page: 98 },
  { id: "_Toc45012051", title: { ur: "مسنون دعائیں", en: "Sunnah Supplications", ar: "الأدعية المسنونة" }, page: 99 },
  { id: "_Toc29194274", title: { ur: "جنات ، جادو ، تعویذ ، عملیات", en: "Jinn, Magic, Amulets & Practices", ar: "الجن والسحر والتعاويذ والعمليات" }, page: 100 },
  { id: "_Toc45012053", title: { ur: "اصلاح و تزکیہ اور مسائل سلوک", en: "Reform, Purification & Issues of Suluk", ar: "الإصلاح والتزكية ومسائل السلوك" }, page: 100 },
  { id: "_Toc45012054", title: { ur: "حقیقت تصوف و سلوک", en: "Reality of Sufism & Suluk", ar: "حقيقة التصوف والسلوك" }, page: 100 },
  { id: "_Toc45012055", title: { ur: "اصلاح", en: "Reform", ar: "الإصلاح" }, page: 103 },
  { id: "_Toc45012056", title: { ur: "کامیابی", en: "Success", ar: "النجاح" }, page: 106 },
  { id: "_Toc45012057", title: { ur: "اصلاح النساء", en: "Reform of Women", ar: "إصلاح النساء" }, page: 106 },
  { id: "_Toc45012058", title: { ur: "تزکیہ", en: "Purification (Tazkiyah)", ar: "التزكية" }, page: 107 },
  { id: "_Toc45012059", title: { ur: "نفس و شیطان / شیطان و ھوی (نفسانی خواہشات )سے اجتناب", en: "Avoiding Nafs & Shaytan / Desires", ar: "اجتناب النفس والشيطان / الهوى" }, page: 108 },
  { id: "_Toc45012060", title: { ur: "فنائیت (فناء در خدا)", en: "Annihilation in God (Fana)", ar: "الفنائية (الفناء في الله)" }, page: 108 },
  { id: "_Toc45012061", title: { ur: "صحبت اولیاء", en: "Company of the Awliya", ar: "صحبة الأولياء" }, page: 109 },
  { id: "_Toc45012062", title: { ur: "تقویٰ", en: "Piety (Taqwa)", ar: "التقوى" }, page: 109 },
  { id: "_Toc45012063", title: { ur: "خوف و رجاء /اللہ سے امید اور اس کا خوف و خیشیت", en: "Fear & Hope in Allah", ar: "الخوف والرجاء / الأمل من الله وخشيته" }, page: 111 },
  { id: "_Toc45012064", title: { ur: "دنیا کی حقیقت", en: "Reality of This World", ar: "حقيقة الدنيا" }, page: 111 },
  { id: "_Toc45012065", title: { ur: "فکر آخرت", en: "Concern for the Hereafter", ar: "فكر الآخرة" }, page: 113 },
  { id: "_Toc45012066", title: { ur: "دعوت و تبلیغ", en: "Calling & Preaching (Dawah)", ar: "الدعوة والتبليغ" }, page: 115 },
  { id: "_Toc45012067", title: { ur: "نیکی و گناہ", en: "Good Deeds & Sins", ar: "النيكي والإثم" }, page: 118 },
  { id: "_Toc45012068", title: { ur: "مفاسد گناہ", en: "Harms of Sin", ar: "مفاسد الذنوب" }, page: 120 },
  { id: "_Toc45012069", title: { ur: "قتل", en: "Killing", ar: "القتل" }, page: 120 },
  { id: "_Toc45012070", title: { ur: "موسیقی", en: "Music", ar: "الموسيقى" }, page: 121 },
  { id: "_Toc45012071", title: { ur: "گناہوں کا علاج", en: "Cure for Sins", ar: "علاج الذنوب" }, page: 121 },
  { id: "_Toc29194278", title: { ur: "اللہ کی نعمتیں", en: "Blessings of Allah", ar: "نعم الله" }, page: 121 },
  { id: "_Toc45012073", title: { ur: "وقت و صحت", en: "Time & Health", ar: "الوقت والصحة" }, page: 122 },
  { id: "_Toc45012074", title: { ur: "شخصیات و اکابر", en: "Personalities & Elders", ar: "الشخصيات والأكابر" }, page: 123 },
  { id: "_Toc45012075", title: { ur: "سیرت آنحضرتﷺ(از ولادت تا وفات )", en: "Life of the Prophet ﷺ (Birth to Death)", ar: "سيرة النبي ﷺ (من الولادة إلى الوفاة)" }, page: 123 },
  { id: "_Toc29194109", title: { ur: "بعثت سے قبل کے حالات و واقعات", en: "Events Before Prophethood", ar: "الأحوال والوقائع قبل البعثة" }, page: 123 },
  { id: "_Toc45012077", title: { ur: "ولادت وبچپن رسول ﷺ", en: "Birth & Childhood of the Prophet ﷺ", ar: "ولادة وطفولة الرسول ﷺ" }, page: 123 },
  { id: "_Toc45012078", title: { ur: "معراج کا سفر", en: "Journey of Miraj", ar: "رحلة المعراج" }, page: 124 },
  { id: "_Toc45012079", title: { ur: "ہجرت رسولﷺ", en: "Migration of the Prophet ﷺ", ar: "هجرة الرسول ﷺ" }, page: 125 },
  { id: "_Toc45012080", title: { ur: "غزوات النبی ﷺ", en: "Battles of the Prophet ﷺ", ar: "غزوات النبي ﷺ" }, page: 126 },
  { id: "_Toc45012081", title: { ur: "معجزات نبیﷺ/معجزات وکرامات", en: "Miracles of the Prophet ﷺ / Miracles & Karamat", ar: "معجزات النبي ﷺ / المعجزات والكرامات" }, page: 127 },
  { id: "_Toc45012082", title: { ur: "حجۃ الوداع", en: "Farewell Pilgrimage", ar: "حجة الوداع" }, page: 128 },
  { id: "_Toc45012083", title: { ur: "وصال نبوت", en: "Passing of the Prophet ﷺ", ar: "وفاة النبي ﷺ" }, page: 128 },
  { id: "_Toc45012084", title: { ur: "مقام اور اوصاف نبوت و سیرت النبیﷺ", en: "Station & Attributes of Prophethood & Sirah", ar: "مقام وأوصاف النبوة وسيرة النبي ﷺ" }, page: 128 },
  { id: "_Toc45012085", title: { ur: "محبت و عشق رسولﷺ", en: "Love & Devotion to the Prophet ﷺ", ar: "محبة وعشق الرسول ﷺ" }, page: 135 },
  { id: "_Toc45012086", title: { ur: "اطاعت رسولﷺ", en: "Obedience to the Prophet ﷺ", ar: "طاعة الرسول ﷺ" }, page: 136 },
  { id: "_Toc45012087", title: { ur: "حقوق مصطفیٰﷺ", en: "Rights of Mustafa ﷺ", ar: "حقوق المصطفى ﷺ" }, page: 136 },
  { id: "_Toc29194125", title: { ur: "بعثت کے مقاصد /آنحضرت ﷺ کی سیرت کا پیغام", en: "Purpose of Prophethood / Message of the Sirah", ar: "مقاصد البعثة / رسالة سيرة النبي ﷺ" }, page: 136 },
  { id: "_Toc29194285", title: { ur: "انبیاء علیہم السلام", en: "Prophets (Peace Be Upon Them)", ar: "الأنبياء عليهم السلام" }, page: 137 },
  { id: "_Toc29194286", title: { ur: "حضرت آدم علیہ السلام", en: "Prophet Adam (AS)", ar: "سيدنا آدم عليه السلام" }, page: 137 },
  { id: "_Toc29194290", title: { ur: "حضر ت نوح علیہ السلام", en: "Prophet Nuh (AS)", ar: "سيدنا نوح عليه السلام" }, page: 137 },
  { id: "_Toc29194289", title: { ur: "حضرت اسماعیل و اسحاق علیھما السلام", en: "Prophets Ismail & Ishaq (AS)", ar: "سيدنا إسماعيل وإسحاق عليهما السلام" }, page: 138 },
  { id: "_Toc45012094", title: { ur: "حضرت موسیٰ وخضر علیہما السلام", en: "Prophets Musa & Khidr (AS)", ar: "سيدنا موسى والخضر عليهما السلام" }, page: 138 },
  { id: "_Toc45012095", title: { ur: "حضرت سلمان علیہ السلام", en: "Prophet Sulayman (AS)", ar: "سيدنا سليمان عليه السلام" }, page: 138 },
  { id: "_Toc45012096", title: { ur: "حضرت ایوب و صالح علیہما السلام", en: "Prophets Ayyub & Salih (AS)", ar: "سيدنا أيوب وصالح عليهما السلام" }, page: 138 },
  { id: "_Toc45012097", title: { ur: "حضرت یوسف علیہ السلام", en: "Prophet Yusuf (AS)", ar: "سيدنا يوسف عليه السلام" }, page: 139 },
  { id: "_Toc29194292", title: { ur: "حضرت عیسیٰ علیہ السلام", en: "Prophet Isa (AS)", ar: "سيدنا عيسى عليه السلام" }, page: 139 },
  { id: "_Toc29194296", title: { ur: "صحابہ و صحابیات رضی اللہ عنہم", en: "Companions (Male & Female) RA", ar: "الصحابة والصحابيات رضي الله عنهم" }, page: 139 },
  { id: "_Toc45012100", title: { ur: "حضرت ابو بکر صدیق﷜", en: "Hazrat Abu Bakr Siddiq (RA)", ar: "سيدنا أبو بكر الصديق رضي الله عنه" }, page: 139 },
  { id: "_Toc45012101", title: { ur: "حضرت فاروق اعظم ﷜", en: "Hazrat Umar Farooq (RA)", ar: "سيدنا الفاروق الأعظم رضي الله عنه" }, page: 140 },
  { id: "_Toc45012102", title: { ur: "حضرت عثمان غنی﷜", en: "Hazrat Uthman Ghani (RA)", ar: "سيدنا عثمان الغني رضي الله عنه" }, page: 140 },
  { id: "_Toc45012103", title: { ur: "حضرت علی کرم اللہ وجہہ", en: "Hazrat Ali (Karam Allahu Wajhahu)", ar: "سيدنا علي كرم الله وجهه" }, page: 141 },
  { id: "_Toc45012104", title: { ur: "فضائل اہل بیت رضی اللہ عنہن", en: "Virtues of the Ahl al-Bayt", ar: "فضائل أهل البيت رضي الله عنهم" }, page: 141 },
  { id: "_Toc45012105", title: { ur: "امہات المؤمنین", en: "Mothers of the Believers", ar: "أمهات المؤمنين" }, page: 141 },
  { id: "_Toc45012106", title: { ur: "بنات رسول ﷺ", en: "Daughters of the Prophet ﷺ", ar: "بنات الرسول ﷺ" }, page: 142 },
  { id: "_Toc45012107", title: { ur: "حسنین کریمین﷠", en: "Hasan & Husayn (RA)", ar: "الحسنين الكريمين رضي الله عنهما" }, page: 142 },
  { id: "_Toc45012108", title: { ur: "دیگر صحابہ کرام ﷢", en: "Other Noble Companions (RA)", ar: "سائر الصحابة الكرام رضي الله عنهم" }, page: 143 },
  { id: "_Toc45012109", title: { ur: "صحابیات", en: "Female Companions", ar: "الصحابيات" }, page: 144 },
  { id: "_Toc29194297", title: { ur: "اکابرین و اولیاء", en: "Elders & Awliya", ar: "الأكابر والأولياء" }, page: 144 },
  { id: "_Toc45012111", title: { ur: "امام اعظم ابوحنیفہ ﷬", en: "Imam Abu Hanifa (RA)", ar: "الإمام الأعظم أبو حنيفة رحمه الله" }, page: 144 },
  { id: "_Toc45012112", title: { ur: "عبد اللہ بن مبارک", en: "Abdullah ibn Mubarak", ar: "عبد الله بن المبارك" }, page: 144 },
  { id: "_Toc29194298", title: { ur: "شیخ عبد القادر جیلانیؒ", en: "Shaykh Abd al-Qadir Jilani (RA)", ar: "الشيخ عبد القادر الجيلاني رحمه الله" }, page: 144 },
  { id: "_Toc29194299", title: { ur: "خواجہ معین الدین چشتیؒ", en: "Khwaja Moinuddin Chishti (RA)", ar: "خواجة معين الدين الجشتي رحمه الله" }, page: 144 },
  { id: "_Toc45012115", title: { ur: "ٹیپو سلطان شہید ﷬", en: "Tipu Sultan Shaheed (RA)", ar: "تيبو سلطان الشهيد رحمه الله" }, page: 145 },
  { id: "_Toc29194302", title: { ur: "حضرت مولانا شاہ اسماعیل شہید ؒ", en: "Maulana Shah Ismail Shaheed (RA)", ar: "المولانا شاه إسماعيل الشهيد رحمه الله" }, page: 145 },
  { id: "_Toc29194300", title: { ur: "حضرت مولانا محمدقاسم نانوتوی رحمہ اللہ", en: "Maulana Muhammad Qasim Nanautawi (RA)", ar: "المولانا محمد قاسم النانوتوي رحمه الله" }, page: 145 },
  { id: "_Toc29194305", title: { ur: "مفتی محمود الحسن صاحب رحمہ اللہ", en: "Mufti Mahmud al-Hasan (RA)", ar: "المفتي محمود الحسن رحمه الله" }, page: 145 },
  { id: "_Toc29194304", title: { ur: "حضرت سید حسین احمد مدنی رحمہ اللہ", en: "Sayyid Hussain Ahmad Madani (RA)", ar: "السيد حسين أحمد المدني رحمه الله" }, page: 145 },
  { id: "_Toc29194301", title: { ur: "حضرت مولانا شبیر احمد عثمانی رحمہ اللہ", en: "Maulana Shabbir Ahmad Uthmani (RA)", ar: "المولانا شبير أحمد العثماني رحمه الله" }, page: 145 },
  { id: "_Toc29194306", title: { ur: "مفتی اعظم پاکستان مفتی شفیع عثمانی صاحب رحمہ اللہ", en: "Grand Mufti of Pakistan Mufti Shafi Uthmani (RA)", ar: "المفتي الأعظم باكستان المفتي شفيع العثماني رحمه الله" }, page: 145 },
  { id: "_Toc29194303", title: { ur: "حضرت مولانا اسعد مدنیؒ", en: "Maulana Asad Madani (RA)", ar: "المولانا أسعد المدني رحمه الله" }, page: 145 },
  { id: "_Toc45012123", title: { ur: "مولانافضل حق خیر آبادی", en: "Maulana Fazl-e-Haq Khairabadi", ar: "المولانا فضل الحق الخير آبادي" }, page: 145 },
  { id: "_Toc45012124", title: { ur: "بابا صندل", en: "Baba Sandal", ar: "بابا صندل" }, page: 145 },
  { id: "_Toc45012125", title: { ur: "شان اولیاء و اکابر", en: "Status of Awliya & Elders", ar: "شأن الأولياء والأكابر" }, page: 145 },
  { id: "_Toc29194308", title: { ur: "اولیاء کی گستاخی", en: "Disrespecting the Awliya", ar: "الإساءة إلى الأولياء" }, page: 146 },
  { id: "_Toc29194309", title: { ur: "اکابر کے اقوال و نصائح", en: "Sayings & Advice of the Elders", ar: "أقوال ونصائح الأكابر" }, page: 146 },
  { id: "_Toc29194310", title: { ur: "مہینے و ایام", en: "Months & Days", ar: "الأشهر والأيام" }, page: 149 },
  { id: "_Toc45012129", title: { ur: "محرم الحرام", en: "Muharram al-Haram", ar: "محرم الحرام" }, page: 149 },
  { id: "_Toc45012130", title: { ur: "صفر المظفر", en: "Safar al-Muzaffar", ar: "صفر المظفر" }, page: 150 },
  { id: "_Toc29194127", title: { ur: "ربیع الاول", en: "Rabi al-Awwal", ar: "ربيع الأول" }, page: 150 },
  { id: "_Toc45012132", title: { ur: "رجب", en: "Rajab", ar: "رجب" }, page: 150 },
  { id: "_Toc29194311", title: { ur: "شعبان المعظم", en: "Shaban al-Muazzam", ar: "شعبان المعظم" }, page: 150 },
  { id: "_Toc29194312", title: { ur: "شب برأت", en: "Shab-e-Barat", ar: "ليلة البراءة" }, page: 151 },
  { id: "_Toc29194313", title: { ur: "رمضان المبارک", en: "Ramadan al-Mubarak", ar: "رمضان المبارك" }, page: 151 },
  { id: "_Toc29194314", title: { ur: "لیلۃ القدر", en: "Laylat al-Qadr", ar: "ليلة القدر" }, page: 153 },
  { id: "_Toc29194317", title: { ur: "شوال", en: "Shawwal", ar: "شوال" }, page: 154 },
  { id: "_Toc29194319", title: { ur: "ذیقعدہ", en: "Dhul-Qadah", ar: "ذو القعدة" }, page: 154 },
  { id: "_Toc29194320", title: { ur: "ذو الحجہ", en: "Dhul-Hijjah", ar: "ذو الحجة" }, page: 154 },
  { id: "_Toc29194322", title: { ur: "خطبہ", en: "Sermon (Khutbah)", ar: "الخطبة" }, page: 154 },
  { id: "_Toc45012141", title: { ur: "عربی خطبات", en: "Arabic Sermons", ar: "الخطب العربية" }, page: 154 },
  { id: "_Toc45012142", title: { ur: "جدیدیات و فکریات", en: "Modernism & Intellectual Trends", ar: "الحداثة والفكريات" }, page: 157 },
  { id: "_Toc45012143", title: { ur: "محاسن اسلام", en: "Beauties of Islam", ar: "محاسن الإسلام" }, page: 157 },
  { id: "_Toc45012144", title: { ur: "امت کے اجتماعی مسائل اور ان کا علاج", en: "Collective Issues of the Ummah & Their Solutions", ar: "المسائل الجماعية للأمة وعلاجها" }, page: 159 },
  { id: "_Toc45012145", title: { ur: "دین کی اشاعت میں خواتین اسلام کا کردار", en: "Role of Muslim Women in Propagating the Faith", ar: "دور المرأة المسلمة في نشر الدين" }, page: 161 },
  { id: "_Toc45012146", title: { ur: "اسلام اور سائنس", en: "Islam and Science", ar: "الإسلام والعلم" }, page: 162 },
  { id: "_Toc45012147", title: { ur: "عقل", en: "Intellect", ar: "العقل" }, page: 162 },
  { id: "_Toc45012148", title: { ur: "جدید تعلیم اور اس کے نتائج", en: "Modern Education & Its Consequences", ar: "التعليم الحديث ونتائجه" }, page: 163 },
  { id: "_Toc45012149", title: { ur: "اسلام و روحانیت بمقابلہ کفر و مادیت", en: "Islam & Spirituality vs Disbelief & Materialism", ar: "الإسلام والروحانية مقابل الكفر والمادية" }, page: 163 },
  { id: "_Toc45012150", title: { ur: "دہشت گردی", en: "Terrorism", ar: "الإرهاب" }, page: 163 },
  { id: "_Toc45012151", title: { ur: "اسلام میں عورت کا مقام اور حقوق", en: "Status & Rights of Women in Islam", ar: "مكانة المرأة وحقوقها في الإسلام" }, page: 163 },
  { id: "_Toc45012152", title: { ur: "مغربی معاشرے میں عورت کا مقام", en: "Status of Women in Western Society", ar: "مكانة المرأة في المجتمع الغربي" }, page: 165 },
  { id: "_Toc45012153", title: { ur: "عورتوں سے متعلق اسلامی احکام و تعلیمات", en: "Islamic Rulings & Teachings Regarding Women", ar: "الأحكام والتعاليم الإسلامية المتعلقة بالنساء" }, page: 165 },
  { id: "_Toc29194251", title: { ur: "اسلامی نظام اور امت مسلمہ", en: "Islamic System & the Muslim Ummah", ar: "النظام الإسلامي والأمة المسلمة" }, page: 166 },
  { id: "_Toc45012155", title: { ur: "حکومت و سیاست/ بین الاقوامی معاملات", en: "Government & Politics / International Affairs", ar: "الحكومة والسياسة / الشؤون الدولية" }, page: 168 },
  { id: "_Toc45012158", title: { ur: "امت مسلمہ کی ذمہ داریاں", en: "Responsibilities of the Muslim Ummah", ar: "مسؤوليات الأمة المسلمة" }, page: 170 },
  { id: "_Toc45012159", title: { ur: "زوال امت کے اسباب", en: "Causes of the Ummah's Decline", ar: "أسباب زوال الأمة" }, page: 171 },
  { id: "_Toc45012160", title: { ur: "وطن عزیز پاکستان", en: "Beloved Homeland Pakistan", ar: "الوطن العزيز باكستان" }, page: 171 },
  { id: "_Toc45012161", title: { ur: "ملکی حالات", en: "National Affairs", ar: "الأحوال الوطنية" }, page: 172 },
  { id: "_Toc45012162", title: { ur: "تفسیر سور وآیات", en: "Exegesis of Surahs & Verses", ar: "تفسير السور والآيات" }, page: 172 },
  { id: "_Toc29194345", title: { ur: "خواتیم و دروس", en: "Conclusions & Lessons", ar: "الخواتيم والدروس" }, page: 176 },
  { id: "_Toc29194346", title: { ur: "ختم قرآن", en: "Completion of the Quran", ar: "ختم القرآن" }, page: 176 },
  { id: "_Toc29194347", title: { ur: "افتتاح بخاری", en: "Inauguration of Bukhari", ar: "افتتاح البخاري" }, page: 176 },
  { id: "_Toc29194348", title: { ur: "ختم بخاری", en: "Completion of Bukhari", ar: "ختم البخاري" }, page: 176 },
  { id: "_Toc29194349", title: { ur: "دروس حدیث", en: "Hadith Lessons", ar: "دروس الحديث" }, page: 177 },
  { id: "_Toc45012168", title: { ur: "ختم و دروس مثنوی", en: "Completion & Lessons of Mathnawi", ar: "ختم ودروس المثنوي" }, page: 177 },
  { id: "_Toc45012169", title: { ur: "مختلف کتابوں سے متعلق خطبات", en: "Sermons on Various Books", ar: "الخطب المتعلقة بكتب مختلفة" }, page: 177 },
  { id: "_Toc29194090", title: { ur: "تعلیم و تعلم", en: "Teaching & Learning", ar: "التعليم والتعلم" }, page: 177 },
  { id: "_Toc45012171", title: { ur: "علم کی ضرورت ، اہمیت و آداب", en: "Need, Importance & Etiquette of Knowledge", ar: "ضرورة العلم وأهميته وآدابه" }, page: 177 },
  { id: "_Toc45012172", title: { ur: "علم کی فضیلت", en: "Virtue of Knowledge", ar: "فضيلة العلم" }, page: 179 },
  { id: "_Toc45012173", title: { ur: "تعلیم نسواں", en: "Education of Women", ar: "تعليم النساء" }, page: 181 },
  { id: "_Toc45012174", title: { ur: "عصری علوم سے متعلق", en: "On Contemporary Sciences", ar: "عن العلوم العصرية" }, page: 181 },
  { id: "_Toc45012175", title: { ur: "جدید تعلیم اور اس کے نتائج", en: "Modern Education & Its Consequences", ar: "التعليم الحديث ونتائجه" }, page: 181 },
  { id: "_Toc45012176", title: { ur: "دینی و دنیاوی علوم کا تقابل", en: "Comparison of Religious & Worldly Sciences", ar: "مقارنة العلوم الدينية والدنيوية" }, page: 182 },
  { id: "_Toc45012177", title: { ur: "علم حدیث (ضرورت، اہمیت و فضائل)", en: "Science of Hadith (Need, Importance & Virtues)", ar: "علم الحديث (الضرورة والأهمية والفضائل)" }, page: 182 },
  { id: "_Toc45012178", title: { ur: "عربی زبان کی اہمیت و فضائل", en: "Importance & Virtues of the Arabic Language", ar: "أهمية اللغة العربية وفضائلها" }, page: 183 },
  { id: "_Toc45012179", title: { ur: "علماء دین کا مقام اور کارنامے", en: "Status & Achievements of Religious Scholars", ar: "مكانة وإنجازات علماء الدين" }, page: 183 },
  { id: "_Toc45012180", title: { ur: "علماء و فضلاء سے خطاب/ ذمہ داریاں اور پیام عمل", en: "Address to Scholars / Responsibilities & Message of Action", ar: "خطاب للعلماء والفضلاء / المسؤوليات ورسالة العمل" }, page: 184 },
  { id: "_Toc45012181", title: { ur: "طلباء مدارس (تعارف، مقام، ذمہ داریاں اور نصائح)", en: "Madrasa Students (Introduction, Status, Duties & Advice)", ar: "طلاب المدارس (التعريف، المكانة، المسؤوليات والنصائح)" }, page: 186 },
  { id: "_Toc45012183", title: { ur: "مدارس کی اہمیت ، ضرورت اور عظمت", en: "Importance, Need & Greatness of Madrasas", ar: "أهمية المدارس وضرورتها وعظمتها" }, page: 188 },
  { id: "_Toc29194104", title: { ur: "مدارس کی ذمہ داریاں/ مدار س کے خلاف سازشیں", en: "Responsibilities of Madrasas / Conspiracies Against Them", ar: "مسؤوليات المدارس / المؤامرات ضدها" }, page: 190 },
  { id: "_Toc29194105", title: { ur: "متفرقات(تعلیم و تعلم)", en: "Miscellaneous (Teaching & Learning)", ar: "متفرقات (التعليم والتعلم)" }, page: 190 },
  { id: "_Toc45012186", title: { ur: "ادیان و مذاہب", en: "Religions & Sects", ar: "الأديان والمذاهب" }, page: 192 },
  { id: "_Toc45012187", title: { ur: "اہلسنت والجماعت اور دیوبندیت", en: "Ahl al-Sunnah wal-Jamaah & Deobandism", ar: "أهل السنة والجماعة والديوبندية" }, page: 192 },
  { id: "_Toc45012188", title: { ur: "منافقین و منافقت", en: "Hypocrites & Hypocrisy", ar: "المنافقون والنفاق" }, page: 192 },
  { id: "_Toc45012189", title: { ur: "عیسائیت", en: "Christianity", ar: "المسيحية" }, page: 192 },
  { id: "_Toc45012190", title: { ur: "یہودیت", en: "Judaism", ar: "اليهودية" }, page: 193 },
  { id: "_Toc45012191", title: { ur: "رافضیت", en: "Rafidism", ar: "الرافضية" }, page: 193 },
  { id: "_Toc45012192", title: { ur: "غیر مقلدیت", en: "Non-Conformism", ar: "الغير مقلدية" }, page: 193 },
  { id: "_Toc45012193", title: { ur: "بریلویت", en: "Barelwism", ar: "البريلوية" }, page: 193 },
  { id: "_Toc45012194", title: { ur: "مماتیت", en: "Mamatism", ar: "المماتية" }, page: 194 },
  { id: "_Toc45012195", title: { ur: "مودودیت", en: "Mawdudism", ar: "المودودية" }, page: 194 },
  { id: "_Toc45012196", title: { ur: "جدیدیت", en: "Modernism", ar: "الحداثة" }, page: 194 },
  { id: "_Toc45012197", title: { ur: "فتن", en: "Tribulations (Fitan)", ar: "الفتن" }, page: 195 },
  { id: "_Toc45012198", title: { ur: "متفرقات", en: "Miscellaneous", ar: "المتفرقات" }, page: 195 },
  { id: "_Toc45012199", title: { ur: "خواب کی حقیقت", en: "Reality of Dreams", ar: "حقيقة الرؤيا" }, page: 200 },
  { id: "_Toc45012200", title: { ur: "وسوسہ ، خیال ، وہم", en: "Whispers, Thoughts & Illusions", ar: "الوسوسة والخيال والوهم" }, page: 200 },
  { id: "_Toc45012201", title: { ur: "گزشتہ اقوام اورمسلمانوں کا ماضی", en: "Past Nations & Muslim History", ar: "الأمم السابقة وماضي المسلمين" }, page: 201 },
  { id: "_Toc45012202", title: { ur: "استخارہ و استشارہ(مشورہ)", en: "Istikhara & Consultation", ar: "الاستخارة والاستشارة" }, page: 201 },
  { id: "_Toc45012203", title: { ur: "داڑھی(وضع قطع، حلیہ)", en: "Beard (Shape & Form)", ar: "اللحية (الشكل والهيئة)" }, page: 201 },
];
